### PR TITLE
Join to the WriterThread after running the tests.

### PR DESCRIPTION
**Pull request by SerialVelocity**
This fixes issues when running with vibe.d (doesn't cause the app to hang anymore)

### CODE REVIEW

**Comment by atilaneves** [comment]
This doesn't compile. Did you mean `WriterThread`?

**Comment by SerialVelocity** [comment]
Yes, I did :)

**Comment by SerialVelocity** [comment]
Ok, there is still the issue (won't happen in the current code) where someone tries to get the ```WriterThread``` after join has been called (or if they have already called get and they use that reference to call methods). Up to you whether that is worth fixing.

**Comment by atilaneves** [comment]
I see what you mean, but I'll figure it out later.

**Comment by SerialVelocity** [comment]
Ah, shame it didn't make it into 0.4.5. I'll continue using my workaround then :)

**Pull request merged**
