### PR TITLE
Fix 218 - Support DMD v2.094.0's `-preview=in` switch

### PR DESCRIPTION
**Pull request by Geod24**
Split into two commits, as after using the switch, I realized some places used `in` for `file`, so I went ahead and unified it.

### CODE REVIEW

**Review by atilaneves — APPROVED** [review]

**Comment by atilaneves** [comment]
This was on my to-do list, and now it's not so... thanks!

**Comment by Geod24** [comment]
Great! Can I have a release so I can update projects ?

**Comment by atilaneves** [comment]
Done.

**Comment by Geod24** [comment]
I also tried to adapt `excel-d` quickly, but it seems it's using a rather old version (with the safety bug), and updating is non trivial (even without `-preview=in`).
Since you want it to be `@safe`, you end up needing to adapt a few functions inside `excel-d`, and a few things inside `unit-threaded`. Mostly adding `scope`.

E.g.
```diff
diff --git a/source/xlld/any.d b/source/xlld/any.d
index 7332e45..5521c63 100644
--- a/source/xlld/any.d
+++ b/source/xlld/any.d
@@ -12,7 +12,7 @@ struct Any {
     alias _impl this;

     ///
-    bool opEquals(Any other) @trusted const {
+    bool opEquals(scope Any other) @trusted const scope {
         import xlld.sdk.xlcall: XlType;
         import xlld.conv.from: fromXlOper;

diff --git a/tests/ut/misc.d b/tests/ut/misc.d
index 0372362..9139ece 100644
--- a/tests/ut/misc.d
+++ b/tests/ut/misc.d
@@ -3,7 +3,6 @@ module ut.misc;
 import test;
 import xlld.any;
 import xlld.sdk.xll;
-import unit_threaded: DontTest;

 @("opEquals str")
 unittest {
@@ -39,8 +38,6 @@ unittest {

 int gAutoCloseCounter;

-
-@DontTest
 void testAutoCloseFunc() nothrow {
     ++gAutoCloseCounter;
 }
```

If you put `@safe` where you want it to be, you'll see some private functions need to be adapted:
```
../../../.dub/packages/unit-threaded-1.0.10/unit-threaded/subpackages/assertions/source/unit_threaded/assertions.d(54,44): Error: @safe function unit_threaded.assertions.shouldEqual!(Any, Any).shouldEqual cannot call @system function unit_threaded.assertions.formatValueInItsOwnLine!(Any).formatValueInItsOwnLine
```

**Pull request merged**
