### PR TITLE
WIP: recursively search for built-in unittest blocks in classes, unions, and structs

### PR DESCRIPTION
**Pull request by shishkander**
Currently limits the check for structs, classes and unions for built-in unittest
blocks.

Work-in-progress. Do not merge.
FTR, i don't work much with github, so if there is better way to show for work-in-progress than pull request, please LMK!

### CODE REVIEW

**Comment by atilaneves** [comment]
Why WIP?

**Comment by shishkander** [comment]
WIP because it spits deprecation warnings like this (dub test in unit-threaded itself):

    ~/tmp/unit-threaded$ dub test --fore
    Unknown command line flags: --fore
    Type "dub test -h" to get a list of all supported flags.
    tandrii@tandrii-glaptop:~/tmp/unit-threaded$ dub test --force
    Running custom 'unittest' configuration.
    Performing "unittest" build using dmd for x86_64.
    unit-threaded 0.6.11+commit.3.gaec9de9: building configuration "unittest"...
    source/unit_threaded/reflection.d(186,26): Deprecation: tests.pass.normal.MyException is not visible from module reflection
    source/unit_threaded/reflection.d(186,26): Deprecation: tests.pass.normal.MyClass is not visible from module reflection
    source/unit_threaded/reflection.d(186,26): Deprecation: tests.pass.normal.Pair is not visible from module reflection
    source/unit_threaded/reflection.d(186,26): Deprecation: tests.pass.register.PrivateTest is not visible from module reflection
    Linking...
    Running ./unit-threaded

**Comment by shishkander** [comment]
That said, i don't really have an idea ho to get rid of these warnings :( 
So, maybe, i can hide the functionality behind the switch? so that if projects are simple, they just look for module-level scope unittests, and otherwise they add extra option for generating ut.d and get deprecation warnings.

    # default, module level unittests only. 
    "preBuildCommands": ["dub run unit-threaded -c gen_ut_main -- -f build/ut.d"]

    # advanced, recursive search in structs, unions, and classes
    "preBuildCommands": ["dub run unit-threaded -c gen_ut_main -- --recursive -f build/ut.d"]


WDYT?

**Comment by atilaneves** [comment]
I checked out your PR branch and added this to addUnitTestsRecursively inside the foreach:

```d
foreach(member; __traits(allMembers, composite)){
    enum notPrivate = __traits(compiles, mixin(member)); //only way I know to check if private
    static if (
        notPrivate &&
        // If visibility of the member is deprecated, the next line still returns true
        // and yet spills deprecation warning. If deprecation is turned into error,
        // all works as intended.
        __traits(compiles, __traits(getMember, composite, member)) &&
       // ... 
```

And... no deprecation warnings, the tests still pass (so your change worked). Do you want to do the honours?

**Comment by shishkander** [comment]
> enum notPrivate = __traits(compiles, mixin(member)); //only way I know to check if private

Brilliant!

**Comment by atilaneves** [comment]
When you update the PR with my proposed change I'll merge it. Thanks!

**Pull request merged**
