### PR TITLE
Fix #295 - Delete stacktrace code

### LINKED ISSUE #295: shouldFail is expensive because it generates stack traces eagerly
`BuiltinTestCase.test` eagerly generates the stack trace string, which is quite expensive.

In my testing (`SIL/lang/bin/ut`), 88% of the runtime of `shouldFail` tests were spent in `localStacktraceToString` vs 12% running the actual test.

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Comment by FeepingCreature** [comment]
Okay, for one that code has been a no-op since https://github.com/atilaneves/unit-threaded/commit/5483971aca13e8a3fb9fc9554a116b10e688eb83

But second, I don't see offhand how this fixes 295? It's still generating the stacktrace in `toString`, right?

**Comment by FeepingCreature** [comment]
Why was that code removed anyway? It builds on 2.104.

**Comment by FeepingCreature** [comment]
See https://github.com/atilaneves/unit-threaded/pull/297

**Comment by atilaneves** [comment]
Thanks for the analysis. I can't remember why I deleted it, I think what's most important is how I was able to in the first place: the relevant test doesn't, and has never, run. One more instance of "always make the tests fail", I guess. And also a little bit of "never test private functions".

**Comment by FeepingCreature** [comment]
Found out in the other PR: it was deleted cause it crashes at runtime. :) The relevant fix is also in the other PR.

They changed `Exception.info` to be malloc allocated.

**Pull request closed without merging**
