### PR TITLE
Meson build

### PR DESCRIPTION
**Pull request by russel**
I created this Meson build so as to make shared objects of Unit Threaded – this enables having the library installed as GtkD is. I have also done this for DInotify.

Sadly Meson/Ninja do not yet support unity builds for D, so it is not yet possible to build the Unit Threaded tests.

If this facility is not interesting, no worries, I'll just keep it as a personal branch.

### CODE REVIEW

**Comment by atilaneves** [comment]
The main problem I have with this is that the source files have to be manually listed in the meson build, which means the build will break if any modules are added/deleted and nobody looks at this (the probability I'll forget is extremely high).

So unless the meson build is checked by travis...

I also severly dislike build systems that force the programmer to list source files - if a file isn't to be compiled, don't put it in the source directory. Is there any of way of globbing whatever's there?

**Comment by russel** [comment]
Meson tries to enforce explicit listing as it makes rebuilds faster. CMake is heading this route. SCons also favours not doing glob to find the list. This is all to do with speed of builds, all of them allow for globbing though. Dub and Cargo (and Gradle) take a different view, assuming a conventional structure and always checking, and thus being slower for rebuilds. I have no idea what Buck and Bazel do.

There's no problem not having this in the main repository, except it will put a block on trying to get unit-threaded into Debian and Fedora. I guess for the general D community this is a null problem.

I can certainly look to making it glob if that is what you would like. For me it is not a big problem, and if it helps get unit-threaded into Debian and Fedora, that is good.

**Comment by atilaneves** [comment]
At the very least the meson build needs to be exercised by travis or it _will_ break.

As for globbing, in CMake the concern isn't speed, and couldn't be since CMake time is not build time. Their concern is forgetting to rerun CMake and therefore not compiling a new file. My answer to that is that if you don't even notice if the new code is there (i.e. because there are no tests for it), then it probably isn't needed. My biases show here - the first thing I write in any D module is:

```d
version(unittest) import unit_threaded;
unittest { 1.shouldEqual(2);
```
Just to make sure the module is being compiled. I also get suspicious when tests keep staying green for too long and randomly make them fail on purpose. Sometimes they don't.

Absent data, I have a hard time believing that checking which files are in the source directories isn't negligible compared to the time it actually takes to compile a file. And this is coming from me, and nothing is more important to me build-wise than incremental builds!

I just cannot fathom why anyone would want to do manually what a machine can automate - I dare say more time is spent by a human updating a list of files than the computer looking for new ones.

I like how the Pony compiler works. You don't pass it files, it just compiles every Pony source file it finds from the current directory downwards by default. It makes one wonder why other compilers require file names...

**Comment by russel** [comment]
I definitely agree that convention over configuration is a better way forward for most cases.

I think the Ninja problem, and hence the Meson and (for me anyway as I do not use Make) CMake, is C and C++.  My belief is that if C and C++ were not in the mix, it would all be much more like Gradle, Dub, Cargo, etc.

I'll amend the Meson build to glob for source. (Rules are there to be broken when appropriate. :-)

**Pull request merged**
