### PR TITLE
Don't run next stage if the previous one failed

### PR DESCRIPTION
**Pull request by drug007**
In non trivial case it's possible that `setup()` fails due to absent test data file for example. So there is no a reason to run `test()` and `shutdown()`. In other way user get error messages from all stages instead of the first failed.

### CODE REVIEW

**Comment by atilaneves** [comment]
Please add a test that checks for this.

**Comment by drug007** [comment]
I can't realize where to place the test. A subproject in `unit-threaded/tests/integration_tests/` and include it into `run.sh`?

**Comment by atilaneves** [comment]
An integration test is probably the easiest for someone not familiar with the code base. You'd have to check that none of the rest of the code runs.

**Comment by drug007** [comment]
Done.

**Pull request merged**
