### PR TITLE
work around dmd bug 19978: shutdown via stdlibc exit instead of returning from main.

### PR DESCRIPTION
**Pull request by FeepingCreature**
Returning from main has a small chance of crashing, which may change the exit code.

See https://issues.dlang.org/show_bug.cgi?id=19978

This is necessary for unittests with generated main to work reliably on CI.

### CODE REVIEW

**Comment by atilaneves** [comment]
I think these changes should go in the unit_threaded.runner.runner.runTestsMain template mixin instead, and change the output of the file to mixin `runTestsMain`.

**Comment by FeepingCreature** [comment]
done

**Comment by atilaneves** [comment]
Should be good to go once the build is fixed.

**Comment by FeepingCreature** [comment]
Added a workaround for the mismangling of the extern(C) symbol in the mixin. Please review again, as it's a bit "clever."

**Pull request merged**
